namespace Cringe.Types.Enums
{
    public enum ClientPacketType : ushort
    {
        Login = 0xFF,
        ChangeAction = 0x0,
        SendPublicMessage = 0x1,
        Logout = 0x2,
        RequestStatusUpdate = 0x3,
        Ping = 0x4,
        StartSpectating = 0x10,
        StopSpectating = 0x11,
        SpectateFrames = 0x12,
        ErrorReport = 0x14,
        CantSpectate = 0x15,
        SendPrivateMessage = 0x19,
        PartLobby = 0x1D,
        JoinLobby = 0x1E,
        CreateMatch = 0x1F,
        JoinMatch = 0x20,
        PartMatch = 0x21,
        MatchChangeSlot = 0x26,
        MatchReady = 0x27,
        MatchLock = 0x28,
        MatchChangeSettings = 0x29,
        MatchStart = 0x2C,
        MatchScoreUpdate = 0x2F,
        MatchComplete = 0x31,
        MatchChangeMods = 0x33,
        MatchLoadComplete = 0x34,
        MatchNoBeatmap = 0x36,
        MatchNotReady = 0x37,
        MatchFailed = 0x38,
        MatchHasBeatmap = 0x3B,
        MatchSkipRequest = 0x3C,
        ChannelJoin = 0x3F,
        BeatmapInfoRequest = 0x44,
        MatchTransferHost = 0x46,
        FriendAdd = 0x49,
        FriendRemove = 0x4A,
        MatchChangeTeam = 0x4D,
        ChannelPart = 0x4E,
        ReceiveUpdates = 0x4F, //4F
        SetAwayMessage = 0x52,
        IrcOnly = 0x54,
        UserStatsRequest = 0x55, //55
        MatchInvite = 0x57,
        MatchChangePassword = 0x5A,
        TournamentMatchInfoRequest = 0x5D,
        UserPresenceRequest = 0x61,
        UserPresenceRequestAll = 0x62,
        ToggleBlockNonFriendDms = 0x63,
        TournamentJoinMatchChannel = 0x6C,
        TournamentLeaveMatchChannel = 0x6D
    }
}