namespace Cringe.Types.Enums
{
    public enum ServerPacketType : short
    {
        UserId = 0x5,
        SendMessage = 0x7,
        Pong = 0x8,
        HandleIrcChangeUsername = 0x9,
        HandleIrcQuit = 0xA,
        UserStats = 0xB,
        UserLogout = 0xC,
        SpectatorJoined = 0xD,
        SpectatorLeft = 0xE,
        SpectateFrames = 0xF,
        VersionUpdate = 0x13,
        SpectatorCantSpectate = 0x16,
        GetAttention = 0x17,
        Notification = 0x18,
        UpdateMatch = 0x1A,
        NewMatch = 0x1B,
        DisposeMatch = 0x1C,
        ToggleBlockNonFriendDms = 0x22,
        MatchJoinSuccess = 0x24,
        MatchJoinFail = 0x25,
        FellowSpectatorJoined = 0x2A,
        FellowSpectatorLeft = 0x2B,
        AllPlayersLoaded = 0x2D,
        MatchStart = 0x2E,
        MatchScoreUpdate = 0x30,
        MatchTransferHost = 0x32,
        MatchAllPlayersLoaded = 0x35,
        MatchPlayerFailed = 0x39,
        MatchComplete = 0x3A,
        MatchSkip = 0x3D,
        Unauthorized = 0x3E,
        ChannelJoinSuccess = 0x40,
        ChannelInfo = 0x41,
        ChannelKick = 0x42,
        ChannelAutoJoin = 0x43,
        BeatmapInfoReply = 0x45,
        Privileges = 0x47,
        FriendsList = 0x48,
        ProtocolVersion = 0x4B,
        MainMenuIcon = 0x4C,
        Monitor = 0x50,
        MatchPlayerSkipped = 0x51,
        UserPresence = 0x53,
        Restart = 0x56,
        MatchInvite = 0x58,
        ChannelInfoEnd = 0x59,
        MatchChangePassword = 0x5B,
        SilenceEnd = 0x5C,
        UserSilenced = 0x5E,
        UserPresenceSingle = 0x5F,
        UserPresenceBundle = 0x60,
        UserDmBlocked = 0x64,
        TargetIsSilenced = 0x65,
        VersionUpdateForced = 0x66,
        SwitchServer = 0x67,
        AccountRestricted = 0x68,
        Rtx = 0x69,
        MatchAbort = 0x6A,
        SwitchTournamentServer = 0x6B
    }
}
