// <auto-generated />
using System;
using Cringe.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cringe.Migrations.PlayerDatabase
{
    [DbContext(typeof(PlayerDatabaseContext))]
    [Migration("20210801194129_AddFriends")]
    partial class AddFriends
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Cringe.Types.Database.Friends", b =>
                {
                    b.Property<int?>("FromId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Cringe.Types.Database.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Playcount")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Pp")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("UserRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Cringe.Types.Database.Friends", b =>
                {
                    b.HasOne("Cringe.Types.Database.Player", "From")
                        .WithMany()
                        .HasForeignKey("FromId");

                    b.HasOne("Cringe.Types.Database.Player", "To")
                        .WithMany()
                        .HasForeignKey("ToId");

                    b.Navigation("From");

                    b.Navigation("To");
                });
#pragma warning restore 612, 618
        }
    }
}
